# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0379fefb8dc9c9d9118bb3d3aaa8d9a8b26bece3c1db72162d9a5c2df03b3ac7eeca8b6696cb15979984f3e231edf4a5daa0b5e926f50abd54a69b3e245b47d1

test:
  secret_key_base: c861dac9233cc935b19a8b64c5043f957b878d479cb5b924ded517d4170930944c3e91899b386ebe856649b15147e572f1fae198f1f851bffd968716581c9c15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
